### ISSUE TITLE
"FileNotFoundError" -- no requirements.txt

### ISSUE THREAD

**Issue by alecpwills** [andersle/pytrr#3] opened 2018-02-23 17:17 UTC
I recently had an issue with `pip install pytrr`:

```
Collecting pytrr
  Using cached pytrr-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_f8e5xhn/pytrr/setup.py", line 90, in <module>
        install_requires=get_requirements(),
      File "/tmp/pip-build-_f8e5xhn/pytrr/setup.py", line 56, in get_requirements
        with openc(filename, encoding='utf-8') as fileh:
      File "/home/alec/anaconda3/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-_f8e5xhn/pytrr/requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_f8e5xhn/pytrr/
```

Changing a line in your setup.py file worked for me, though (as per this [similar problem](https://stackoverflow.com/questions/42530309/no-such-file-requirements-txt-error-while-installing-quartz-module)):

In setup.py, in `def get_requirements()` I changed
```
 filename = os.path.join(here, 'requirements.txt')
```
to 
```
filename = os.path.join(here, 'pytrr.egg-info/requires.txt')
```
which fixed the problem and allowed usage of the package.

**Comment by andersle** [comment] 2018-02-24 00:19
Many thanks for submitting this issue!

I had forgotten to include the file `requirements.txt` in the `MANIFEST.in` file so it was not included in the distribution. I have updated this file and uploaded a new version to [pypi](https://pypi.python.org/pypi/pytrr/0.4.1).

Downloading the old version (e.g. `pip download pytrr==0.4.0`) should fail while downloading the more recent package (`pip download pytrr==0.4.1`) should now work.

Also, comparing the two downloaded source distributions by the commands above, `pytrr-0.4.0.tar.gz` and `pytrr-0.4.1.tar.gz`, one can see that the latter now includes the `requirements.txt` file.

Again, thanks for submitting and I hope the issue is fixed now.

**Closed as completed by andersle** 2018-02-24 00:19 UTC
